synergy: Autospec creation for update from version 1.13.0 to version 1.14.6.19
Alvaro Soto (1):
      Fix typo in X Keyboard log warning on Linux (#7191)

Andrea Candian (1):
      Update README.md

Andrey Batyiev (21):
      SYNERGY 512 SonarCloud vulnerabilities in Synergy-Core (#6971)
      SYNERGY-511 SonarCloud security hotspots in Synergy-core (#6972)
      SYNERGY-835 Synergy stops working (#6975)
      SYNERGY-885 mac client listens on ipv4 only but attempts to connect on ipv6 (#6983)
      SYNERGY-907 Client tray language switcher reverts to EN (#6989)
      SYNERGY-969 Detect if Linux is running with Wayland, and display a wa… (#6999)
      SYNERGY-970 Synergy1. User is not able to connect to server using ipv… (#7005)
      SYNERGY-885 mac client listens on ipv4 only but attempts to connect on ipv6 (#7008)
      SYNERGY-907 Client tray language switcher reverts to EN (#7011)
      Synergy 907 client tray language switcher reverts to en (#7014)
      SYNERGY-1050 Synergy1. Floating issue. User is not able to paste to c… (#7057)
      Synergy 1081 synergy1. buffer was not updated in case user copies on server and then copies on client and paste (#7058)
      SYNERGY-1027 When clicking on "Save" preferences, automatically apply… (#7068)
      SYNERGY-1036-Radio-button-style-issue (#7070)
      Synergy 1161 when clicking on save preferences on configure server window, automatically apply all the new settings (#7074)
      Synergy 1161 when clicking on save preferences on configure server window, automatically apply all the new settings (#7077)
      SYNERGY-1133 Clipboard sharing re-enables automatically (#7078)
      Synergy 1161 when clicking on save preferences on configure server window, automatically apply all the new settings (#7081)
      Hot-Fix-unittest-CMakeFileList (#7091)
      Synergy 907 client tray language switcher reverts to en (#7038)
      SYNERGY-854 Compiling with MSVC 2014 causes error C2280 (#7099)

Daun Chung (3):
      SYNERGY-542 language record (#6990)
      SYNERGY-1043 (#7084)
      flatpack workflow to build flatpak installer (#7177)

Idar Lund (1):
      Update README.md (#6967)

Ignacio Rodriguez (4):
      modified Changelog
      Handling pre-main window status notifications
      reflecting status post-init
      resolved code smell reported

Ignacio Rodríguez (10):
      Ubuntu Tray Icon at Start Up (#6889)
      Remaining SonarCloud Bugs (#6900)
      Synergy 591 remaining sonarcloud bugs in synergy core (#6915)
      Removing positional union initialisation (#6918)
      Main Window receives screen name change (#6916)
      Document CLI arguments (#6909)
      Save global settings (#6903)
      Synergy 722 remove synchronize screen saver and enable drag  (#6912)
      Duplicating text spaces after dot only for Mac (#6914)
      Save configuration on apply (#6907)

Igor Sikachyna (28):
      SYNERGY-956 - Resolve code scanning issues (#7006)
      SYNERGY-988 Mac client does not scroll in natural direction (#7012)
      SYNERGY-124 - Start synergy if the service is idle (#7015)
      SYNERGY-993 - Remove code related to the screen saver synchronization functionality (#6998)
      SYNERGY-538 - Allow Windows to go to sleep depending on system preferences (#6997)
      SYNERGY-856 - Add option to prevent client from sleeping (#7001)
      SYNERGY-1017 - Added a basic IO registry search for secure input presence
      SYNERGY-1017 - Add notification
      SYNERGY-1017 - Add secure input detection and notification
      SYNERGY-1017 - Remove redundant code changes
      SYNERGY-1017 - Update secure input message
      SYNERGY-1017 - Update changelog
      SYNERGY-1017 - Resolve code smell
      SYNERGY-1017 - Remove const
      SYNERGY-1017 - Simplify the check for secure input
      SYNERGY-1017 - Remove redundant imports
      SYNERGY-1017 - Add an option to stop the app which causes secure input
      SYNERGY-1006 - Added template mode for icons on Big Sur and higher
      SYNERGY-1006 - Update changelog
      SYNERGY-1006 - Resolve code smell
      SYNERGY-1006 - Remove redundant temp variable
      SYNERGY-1032 - Use native notifications for secure input on MacOS (#7041)
      SYNERGY-1032 - Send secure input notifications to client (#7043)
      SYNERGY-988 - Normalize scrolling direction (#7044)
      SYNERGY-1032 - Add MacOS version check and disabl UserNotification library if needed (#7046)
      SYNERGY-856 - Force prevent sleep (#7047)
      SYNERGY-1060 - Toast notifications on windows (#7052)
      SYNERGY-1061 - Add libnotify on Linux and create notifications (#7055)

Jonathan Anderson (1):
      Fix crash due to out-of-order frees. (#7208)

Kyle Bloom (33):
      Core builds (#6908)
      Fix path on mac and linux
      Change openssl path
      Mac build failures (#6922)
      Revert openssl changes (#6926)
      Raspberry pi (#6941)
      Fix package glob (#6945)
      Add stage to file name (#6946)
      SYNERGY-833 Add extra enterprise validation (#6951)
      OpenSSL find package (#6952)
      SYNERGY-801 Add self-hosted runner for OSX 10.13 (#6962)
      Synergy 801 fix filename (#6965)
      Synergy 801 wrong folder (#6966)
      Add missing make instruction (#6974)
      Add M1 workflow (#7098)
      Add missing build_version for m1 mac (#7109)
      SYNERGY-1254 Fix core builds (#7103)
      SYNERGY3-150 Fix unstable build for windows core (#7148)
      Change binary store (#7156)
      Brew bundle (#7161)
      Synergy3-1505 Add new distros to CI (#7162)
      Add changelogs to deb's (#7167)
      Remove tmpdir from dh to fix builds on 22.04 (#7169)
      Extract 3 segment version from long version string (#7168)
      Fix build issue with raspberry pi's (#7173)
      Remove specific package names for changelog
      Show all Raspberry PI builds (#7174)
      Add fedora 36 build (#7181)
      Change action condition to release
      Change flatpak name (#7187)
      Update macos workflow to use macos-latest (#7210)
      Update azure pipelines to use latest macos image (#7213)
      Upgrade the default hashing algorithm (#7241)

Mathieu Aubin (1):
      zip filename fix (#7154)

Max (1):
      Fixed typo in Changelog.

Michał Górny (1):
      Support building against system pugixml (#7119)

Nick Bolton (16):
      Create FUNDING.yml
      Update bug_report.md
      Update bug_report.md
      Update feature_request.md
      #StandWithUkraine
      Add link to Synergy Vintage
      Fix link in readme
      More sensible version URL
      Fixed purchase URL
      Fixed help URL
      Fixed contact URL
      Fixed account URL
      Very minor tidy up of ChangeLog
      Fixed minor typos in ChangeLog
      Update ChangeLog
      Create stale-issues.yml

Pedro Navarro (2):
      Pasting text copied from Linux results in doubled lines (#7144)
      Address issues with modifiers and dead keys (#7149)

Sergei Trofimovich (1):
      add missing <cstdint> includes for SIZE_MAX (#7237)

Serhii Hadzhilov (158):
      SYNERGY-723 Don't use the word “Version” for release names.
      Update ChangeLog
      SYNERGY-799 Update header message
      SYNERGY-799 Remove bottom label
      SYNERGY-799 Decrease grid margins
      SYNERGY-799 Change grid size
      SYNERGY-799 Button add computer has been added
      SYNERGY-799 Implement add computer button
      SYNERGY-799 Remove unused files
      SYNERGY-799 Update screen name
      SYNERGY-799 Rearrange "Modifier keys" group
      SYNERGY-799 Fix Screen settings window
      SYNERGY-799 Rearrange advanced settings tab
      SYNERGY-799 Fix margins for advanced tab
      Update ServerConfigDialogBase.ui
      Update ChangeLog
      SYNERGY-799 Move computer name
      SYNERGY-799 Move common settings
      SYNERGY-799 Security section
      SYNERGY-799 Logs section
      SYNERGY-799 Set default size
      SYNERGY-799 Move “Elevate” to the “Advanced” section
      SYNERGY-799 Update browse buttons
      SYNERGY-799 Update security controls enabling logic
      SYNERGY-799 Don't select type by default
      SYNERGY-799 Fixed issue with screen name validation
      SYNERGY-799 Fix code smell. Removed unused autoconfig function.
      SYNERGY-799 Restore lost functionality
      SYNERGY-918 Manual config error in client mode
      Update ChangeLog
      SYNERGY-799 Client connection errors
      SYNERGY-799 Show message even if parent is hidden or minimized
      SYNERGY-936 New message for expired licenses
      SYNERGY-936 Fixed problem when message text is reset
      SYNERGY-694 Issues with clients messages
      SYNERGY-694 Prevent client duplication.
      SYNERGY-694 Fix code smell
      SYNERGY-936 Fix a gap between label and computer name
      SYNERGY-936 Fixed gaps in IPs
      SYNERGY-936 Fix links
      SYNERGY-936 Change Log to Logs and fix position.
      SYNERGY-936 Fix gap for linux system
      SYNERGY-936 Remove fix for fixes group
      SYNERGY-936 Fix spacing on Linux
      SYNERGY-936 Arial font
      SYNERGY-936 Fix font size
      SYNERGY-936 Fix logs group
      SYNERGY-936 Fix activation window
      SYNERGY-936 Attribute should be set before the application is run.
      SYNERGY-936 Replace titles with labels
      SYNERGY-936 Fixed styles for logs
      SYNERGY-936 Replace QGroupBox with QFrame on MainWindow
      SYNERGY-936 Fix panels cutting on Linux
      SYNERGY-936 MainWindow aligment
      SYNERGY-936 QFrames for screen settings
      SYNERGY-936 Fix font size
      SYNERGY-936 Fix aliases group
      SYNERGY-936 Update computer name validation
      SYNERGY-936 Fix validation issue on screen settings window
      SYNERGY-936 Screen settings window size
      SYNERGY-936 Controls resizing
      SYNERGY-936 Update ChangeLog
      SYNERGY-936 Layout refactoring
      SYNERGY-936 Fix layout size for windows
      SYNERGY-936 Fix layout spacing
      SYNERGY-936 Replace qgroups with qframes
      SYNERGY-936 New upgrade window
      SYNERGY-936 Rename "settings" to "Preferences"
      SYNERGY-936 Update ChangeLog
      SYNERGY-694 Handle client name duplication
      SYNERGY-694 Reduce connection timeout to 2 seconds
      Update ChangeLog
      SYNERGY-966 Additional UI tweaks
      Update ChangeLog
      SYNERGY-979 Add clients by priority
      SYNERGY-979 Fix typos
      Update ChangeLog
      SYNERGY-979 Fix code smell
      SYNERGY-914 Add openssl dependency for rpm
      Update ChangeLog
      SYNERGY-661 Fix Ubuntu 16.04 pipeline in Azure
      Update ChangeLog
      SYNERGY-999 Fix script that generates version number
      Update ChangeLog
      SYNERGY-1005 Add Fedora 33 to build and release pipeline
      Update ChangeLog
      SYNERGY-957 Update openssl for windows builds
      Update ChangeLog
      SYNERGY-957 Install openssl
      SYNERGY-928 Update ChangeLog
      SYNERGY-928 Wrong encoding form macOS
      Update ChangeLog
      Update ChangeLog
      Revert "Update ChangeLog"
      SYNERGY-1047 Scroll doesn't work in case of macOS is server
      Update ChangeLog
      SYNERGY-1088 MacOS client ignores prevent sleeping option
      SYNERGY-1088 Windows client ignores prevent sleeping option
      Update ChangeLog
      SYNERGY-1013 Ability to run synergy as a pre-login agent
      Update ChangeLog
      SYNERGY-1057 Add trace if the system can't open file with trusted fingerprints
      SYNERGY-1057 Update ChangeLog.txt
      SYNERGY-1057 Fix code smell
      SYNERGY-1099 Modifier keys don't work on Microsoft Remote Desktop
      Update ChangeLog
      Update ChangeLog
      SYNERGY-1247 CapsLock doesn't work on Microsoft Remote Desktop
      Update ChangeLog
      SYNERGY-1215 Update account and upgrade links
      Update ChangeLog
      SYNERGY-1216 the system duplicates hotkeys in setup
      Update ChangeLog
      SYNERGY-1218 Wrong window title after open preferences
      Update ChangeLog
      SYNERGY-1307 Language reading on linux (#7114)
      SYNERGY-1307 Prevent notifications if language reading fails (#7115)
      Release V1.14.2
      SYNERGY-1397 MacOS function keys (#7135)
      SYNERGY-1454 Scroll direction (#7140)
      SYNERGY-1454 Scroll direction refactoring (#7141)
      SYNERGY3-17 Stop on login screen (#7143)
      fix: SYNERGY3-203 Synergy 1 business (#7157)
      SYNERGY3-203 Build fix (#7160)
      SYNERGY1-1478 Fix compilation issues (#7163)
      SYNERGY1-1497 Fix memory leaks (#7164)
      SYNERGY-1-1494 Replace notifications with logs (#7166)
      SYNERGY1-1497 memory leaks in synergyc on mac os (#7170)
      SYNERGY1-1497 Memory leaks in copy/paste and drag and drop functionality (#7175)
      SYNERGY1-1497 Fix memory leak on macOS (#7178)
      SYNERGY1-1536 Disable drag and drop by default (#7179)
      SYNERGY1-963 Remove TLS unused options from the GUI on Synergy Client (#7182)
      SYNERGY1-1511 Refactoring for v3 licenses  (#7183)
      SYNERGY1-1544 Issue with TLS options when user switches to system profile (#7185)
      SYNERGY1-1545 Accept business licenses in basic/pro builds (#7188)
      SYNERGY1-1555 maintenance licences (#7190)
      Support for maintenance licenses in China (#7193)
      Special contributor mentions on the about screen (#7197)
      Move API URL to config file (#7198)
      Use vertical scroll on the about screen (#7199)
      Release v1.14.5 (#7219)
      Add ability to initiate connection from server (#7222)
      Initiate TLS connection from server (#7225)
      Add ability to reconnect from server side (#7226)
      Update visibility for mode checkbox during settings loading. (#7228)
      Fix issue with reconnection when server initiate TLS connection.  (#7230)
      Use default value for InitiateConnectionFromServer option during switching between scopes (#7232)
      Single app for server and client (#7239)
      Add manifest for synergy-core to fix problem with dpi on windows (#7240)
      Fix tls certificate generation for flatpak (#7242)
      Add firewall exception for synergy client (#7248)
      Fix rpm builds (#7249)
      Update Version.cmake
      Add builds for Fedora 37 and 38
      Update Version.cmake
      Fix openssl installation
      Fix openssl installation for x64
      Fix backward compatibility for m1 build (#7262)

SerhiiGadzhilov (53):
      SYNERGY-706 Release 1.13.0-stable (#6892)
      SYNERGY-400 Unify artifacts names (#6896)
      Update Version.cmake (#6898)
      Fixed #6839 Wrong text encoding in iMessage (#6927)
      SYNERGY-722 Remove information about drag and drop from Log (#6928)
      Synergy 579 auto hide on start changing to false when open syn (#6930)
      SYNERGY-801 Update build pipeline to support macOS 10.13 (#6931)
      SYNERGY-677 Application loses settings (#6933)
      SYNERGY-719 Text on welcome screen on macOS is shown without spaces (#6934)
      SYNERGY-677 Application loses settings. Don't save settings into memory if the file is not writable.  (#6935)
      SYNERGY-677 Common settings should always be saved. (#6936)
      SYNERGY-734 Modern C++ compiler for centOS7 (#6937)
      SYNERGY-687 Remove auto config message (#6938)
      SYNERGY-736 Update pipelines to use correct credentials (#6939)
      SYNERGY-688 all the text in all the windows should have the same font and size (#6942)
      SYNERGY-691 Systray icon is incorrect for macOS Big Sur (#6944)
      SYNERGY-821 The system doesn't recognize old settings (#6947)
      SYNERGY-826 Add a new option SYNERGY_AUTOCONFIG (#6949)
      SYNERGY-786 The system does not update server name in Server configuration (#6953)
      SYNERGY-793 move language selection to advanced section (#6954)
      Merge V1.13.1 (#6955)
      SYNERGY-786 The system resets server name (#6961)
      SYNERGY-881 System loses synchronisation between settings and configuration (#6968)
      SYNERGY-799 Update synergy UI. Setup wizard (#6959)
      SYNERGY-799 Add validation for aliases (#6969)
      SYNERGY-799 Update Synergy UI. Main screen (#6973)
      Fix windows builds (#6976)
      SYNERGY-694 Setup client configuration (#6981)
      SYNERGY-694 Setup client configuration issues (#6987)
      SYNERGY-936 Set min size
      SYNERGY-991 Clipboard sharing doesn't work on Linux system
      Update ChangeLog
      SYNERGY-1003 Connection processing for name with several ips (#7013)
      SYNERGY-1007 Update version numbers (#7018)
      SYNERGY-928 Wrong encoding for text copied between linux and windows
      Merge changes from V1.14.0 (#7032)
      SYNERGY-1026 Add Ubuntu 21.04 (#7037)
      SYNERGY-972 Add Fedora 34 (#7035)
      SYNERGY-1088 Linux client ignores prevent sleep option
      SYNERGY-1088 Fix code smells
      SYNERGY-1088 Fix code smells
      SYNERGY-1089 No notification between clients (#7064)
      SYNERGY-1085 Notificatons for unknown applications (#7066)
      SYNERGY-124 Windows client doesn't resume connection after sleep (#7082)
      SYNERGY-1229 Synergy is running after quit on Linux
      Fix code smell
      SYNERGY-1232 No configuration available on Windows system (#7100)
      SYNERGY-1232 Issues with ssl certificate path (#7101)
      Synergy 1267 endless notifications during connection (#7104)
      Synergy 571 wrong characters on client for unicode (#7108)
      SYNERGY-1287 display language notifications only on client side (#7111)
      Synergy 1298 client can't connect to previous server version (#7112)
      SYNERGY-1298 Fix endless notifications during connection (#7113)

Toru Yamada (1):
      Support "Kana" and "Eisu" keys on Japanese Apple Pro Keyboard (JIS) (#7040)